/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/emergencies/{emergencyId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a resource for an emergency */
        post: operations["ResourcesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a resource */
        post: operations["ResourcesController_verifyResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{resourceId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a resource */
        post: operations["ResourcesController_publishResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/coordination/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the coordination queue for an emergency */
        get: operations["CoordinationController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/{emergencyId}/public/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published (active) resources for an emergency */
        get: operations["PublicController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active emergencies */
        get: operations["EmergenciesController_list"];
        put?: never;
        /** Create an emergency */
        post: operations["EmergenciesController_createEmergency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emergencies/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get emergency by slug */
        get: operations["EmergenciesController_getBySlugRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterResourceDto: {
            /**
             * @example collection_point
             * @enum {string}
             */
            type: "collection_point" | "delivery_point" | "warehouse" | "transport" | "supplier" | "venue";
            /**
             * @example origin
             * @enum {string}
             */
            side: "origin" | "destination";
            /** @example Cruz Roja Madrid */
            name: string;
        };
        RegisterResourceResponseDto: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
        };
        VerifyResourceDto: {
            /**
             * @description Must not be "unverified"
             * @example verified
             * @enum {string}
             */
            level: "unverified" | "verified" | "official";
        };
        ResourceViewDto: {
            /**
             * Format: uuid
             * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
             */
            id: string;
            /**
             * @example collection_point
             * @enum {string}
             */
            type: "collection_point" | "delivery_point" | "warehouse" | "transport" | "supplier" | "venue";
            /**
             * @example origin
             * @enum {string}
             */
            side: "origin" | "destination";
            /** @example Cruz Roja Madrid */
            name: string;
            /**
             * @example verified
             * @enum {string}
             */
            verificationLevel: "unverified" | "verified" | "official";
            /**
             * @example active
             * @enum {string}
             */
            publicStatus: "hidden" | "active" | "saturated" | "paused" | "closed";
        };
        CreateEmergencyDto: {
            /** @example Emergencia sísmica — Venezuela */
            name: string;
            /**
             * @description URL-safe slug (lowercase letters, digits, hyphens). Auto-generated from name if omitted.
             * @example venezuela
             */
            slug?: string;
            /**
             * @description ISO 3166-1 alpha-2 country code
             * @example VE
             */
            country: string;
        };
        CreateEmergencyResponseDto: {
            /** @example 11111111-1111-4111-8111-111111111111 */
            id: string;
            /** @example venezuela */
            slug: string;
        };
        EmergencyViewDto: {
            /** @example 11111111-1111-4111-8111-111111111111 */
            id: string;
            /** @example Emergencia sísmica — Venezuela */
            name: string;
            /** @example venezuela */
            slug: string;
            /** @example VE */
            country: string;
            /** @example active */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ResourcesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterResourceDto"];
            };
        };
        responses: {
            /** @description Resource registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResourceResponseDto"];
                };
            };
            /** @description Invalid request body or UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourcesController_verifyResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyResourceDto"];
            };
        };
        responses: {
            /** @description Resource verified */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid verification level or UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourcesController_publishResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource UUID */
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource published */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not verified yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CoordinationController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of resources in queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceViewDto"][];
                };
            };
            /** @description Emergency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Emergency UUID */
                emergencyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of published resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceViewDto"][];
                };
            };
        };
    };
    EmergenciesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active emergencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyViewDto"][];
                };
            };
        };
    };
    EmergenciesController_createEmergency: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmergencyDto"];
            };
        };
        responses: {
            /** @description Emergency created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEmergencyResponseDto"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmergenciesController_getBySlugRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Emergency found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmergencyViewDto"];
                };
            };
            /** @description Emergency not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
