import {
  pgTable,
  uuid,
  text,
  timestamp,
  doublePrecision,
  jsonb,
  boolean,
} from 'drizzle-orm/pg-core';

export const resourcesTable = pgTable('resources', {
  id: uuid('id').primaryKey(),
  emergencyId: uuid('emergency_id').notNull(),
  type: text('type').notNull(),
  stage: text('stage').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  address: text('address').notNull(),
  latitude: doublePrecision('latitude').notNull(),
  longitude: doublePrecision('longitude').notNull(),
  ownerUserId: uuid('owner_user_id').notNull(),
  ownerOrganizationId: uuid('owner_organization_id'),
  verificationLevel: text('verification_level').notNull(),
  publicStatus: text('public_status').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  // enriched fields (0018_resources_enrich)
  contact: text('contact'),
  schedule: text('schedule'),
  manager: text('manager'),
  accepts: text('accepts').array(),
  sourceName: text('source_name'),
  externalId: text('external_id'),
  externalUpdatedAt: timestamp('external_updated_at', { withTimezone: true }),
  country: text('country'),
  city: text('city'),
  raw: jsonb('raw'),
  // destinatario final (0023_resource_recipient_role)
  isFinalRecipient: boolean('is_final_recipient').notNull().default(false),
  recipientType: text('recipient_type'),
});
